server:
  port: 8084

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/event/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: false


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
