server:
  port: 8084

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: event-service
              uri: lb://event-service
              predicates:
                - Path=/api/event/**
            - id: registration-service
              uri: lb://registration-service
              predicates:
                - Path=/api/registration/**
            - id: review-service
              uri: lb://review-service
              predicates:
                - Path=/api/reviews/**
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "*"
                allowedMethods:
                  - "*"
                allowedHeaders:
                  - "*"
                allowCredentials: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/